apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: tile-based-training
deploy:
  helm:
    releases:

      - name: tile-based-training-localstack
        remoteChart: localstack/localstack
        namespace: tile-based-training
        createNamespace: true
        setValues:
          service.type: LoadBalancer

      # Code-Server with Calrissian
      - name: code-server
        chartPath: ../charts/coder
        namespace: tile-based-training
        createNamespace: true
        setValues:
          service.type: LoadBalancer
          storageClassRWX: "standard"
          coder.coderImage: eoepca/pde-code-server:1.0.0
          coder.workspace: machine-learning-process
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login,
        }
       
      # MLflow
      - name: my-mlflow  # OSError: [Errno 30] Read-only file system: '/mlflow'
        remoteChart: community-charts/mlflow
        namespace: tile-based-training
        createNamespace: true
        setValues:
          service.type: ClusterIP
          service.port: 5000
          ingress.enabled: true
          ingress.className: standard
          resources.limits.memory: 5Gi
          resources.limits.cpu: 500m
          resources.requests.cpu: 200m
          resources.requests.memory: 3Gi
          backendStore:
            databaseMigration: true  # Enable database migration to ensure schema is up-to-date
            postgres:
              enabled: false  # Disable PostgreSQL
            mysql:
              enabled: false  # Disable MySQL
          artifactRoot: 
            proxiedArtifactStorage: false  # Disable proxied artifact storage access
            azureBlob:
              enabled: false  # Disable Azure Blob Storage
            s3:
              enabled: false  # Disable AWS S3
            gcs:
              enabled: false  # Disable Google Cloud Storage
          
            

portForward:
  - resourceType: service
    resourceName: my-mlflow
    address: localhost
    namespace: tile-based-training
    port: 5000
    localPort: 5000

  
  - resourceType: service
    resourceName: code-server-service # code server service name in ../chart/coder/templates/coder.yaml
    namespace: tile-based-training
    address: localhost
    port: 8080
    localPort: 8000  
