apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-advanced-tooling

build:
  tagPolicy:
    envTemplate:
      template: 2h

  artifacts:
    - image: ttl.sh/eoap-advanced-tooling-coder 
      context: .
      docker:
        dockerfile: Dockerfile.coder

deploy:
  helm:
    releases:
      - name: eoap-advanced-tooling
        chartPath: ../charts/coder
        namespace: eoap-advanced-tooling
        createNamespace: true
        setValues:
          coder.coderImage: ttl.sh/eoap-dask-gateway-coder:2h
          coder.workspace: advanced-tooling
          coder.storageClassName: openebs-kernel-nfs-scw
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          coder.securityContext.privileged: false
          calrissian.enabled: true
          calrissian.storageClassName: openebs-kernel-nfs-scw
          skaffold.enabled: true
          kaniko.enabled: true
          
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
      - name: eoap-advanced-tooling-localstack
        remoteChart: localstack/localstack
        namespace: eoap-advanced-tooling
        createNamespace: true
        setValues:
          service.type: ClusterIP

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-advanced-tooling 
    address: localhost
    port: 8080
    localPort: 8000