apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-how-to

deploy:
  helm:
    releases:
      - name: eoap-how-to
        chartPath: ../charts/coder
        namespace: eoap-how-to
        createNamespace: true
        setValues:
          coder.workspace: how-to
          coder.storageClassName: standard #openebs-kernel-nfs-scw
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true
          calrissian.storageClassName: standard #openebs-kernel-nfs-scw
          calrissian.imagePullSecrets: []
          skaffold.enabled: True
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-how-to
    port: 8080
    localPort: 8000