apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-how-to

build:
  artifacts:
    - image: appimage
  
deploy:
  helm:
    releases:
      - name: eoap-how-to
        chartPath: ../charts/coder
        namespace: eoap-how-to
        createNamespace: true
        setValueTemplates:
          coder.coderImage: "{{.IMAGE_REPO_appimage}}/{{.IMAGE_TAG_appimage}}@{{.IMAGE_DIGEST_appimage}}"
        setValues:
          coder.workspace: how-to
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          skaffold.enabled: True
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-how-to
    port: 8080
    localPort: 8000