apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-event-driven
    
deploy:
  helm:
    releases:
      # argo workflows
      - name: eoap-argo-workflows
        remoteChart: argo/argo-workflows
        namespace: eoap-event-driven
        createNamespace: true
        setValues:
          crds.install: false
          server.authModes: [server]
          singleNamespace: true
          workflow:
            serviceAccount:
              create: true
              name: "argo"
            rbac:
              create: true
          controller:
            workflowNamespaces:
              - eoap-event-driven
            workflowDefaults:
              spec:
                serviceAccountName: argo

      # argo events
      - name: eoap-argo-events
        remoteChart: argo/argo-events
        namespace: eoap-event-driven
        createNamespace: true
        setValues:
          crds.install: false


      - name: eoap-redis
        chartPath: ./charts/redis
        namespace: eoap-event-driven
        createNamespace: true
        setValues:
          maxMemory: 2mb
          maxMemoryPolicy: allkeys-lru
          port: 6379
        
      # argo cwl runner

      # argo water bodies

      # local chart for event bus/source/sensor - NEEDS TESTING
      - name: eoap-event-driven
        chartPath: ./charts/event-driven
        namespace: eoap-event-driven
        createNamespace: true
        setValues:
          jetstreamReplicas: 3
          jetstreamVolumeSize: 1Gi
          streamName: STREAM


      - name: eoap-event-driven-coder
        chartPath: ../charts/coder
        namespace: eoap-event-driven
        createNamespace: true
        setValues:
          coder.coderImage: eoepca/pde-code-server:1.0.0
          coder.workspace: eoap-event-driven
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true 
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
      # - name: eoap-event-driven-localstack
      #   remoteChart: localstack/localstack
      #   namespace: eoap-event-driven
      #   createNamespace: true
      #   setValues:
      #     service.type: ClusterIP

portForward: 
  - resourceType: service
    resourceName: eoap-argo-workflows-server
    namespace: eoap-event-driven
    address: localhost
    port: 2746
    localPort: 2746  
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-event-driven
    address: localhost
    port: 8080
    localPort: 8000  