{{- if .Values.kaniko.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: kaniko-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgImZha2UucmVnaXN0cnkuaW8iOiB7DQogICAgICAgICAgICAidXNlcm5hbWUiOiAiZmFrZXVzZXIiLA0KICAgICAgICAgICAgInBhc3N3b3JkIjogImZha2VwYXNzd29yZCIsDQogICAgICAgICAgICAiZW1haWwiOiAiZmFrZUBleGFtcGxlLmNvbSIsDQogICAgICAgICAgICAiYXV0aCI6ICIiDQogICAgICAgIH0NCiAgICB9DQp9
---
apiVersion: v1
kind: Secret
metadata:
  name: ttl-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgImZha2UucmVnaXN0cnkuaW8iOiB7DQogICAgICAgICAgICAidXNlcm5hbWUiOiAiZmFrZXVzZXIiLA0KICAgICAgICAgICAgInBhc3N3b3JkIjogImZha2VwYXNzd29yZCIsDQogICAgICAgICAgICAiZW1haWwiOiAiZmFrZUBleGFtcGxlLmNvbSIsDQogICAgICAgICAgICAiYXV0aCI6ICIiDQogICAgICAgIH0NCiAgICB9DQp9
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
imagePullSecrets:
  - name: kaniko-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko-rolebinding
subjects:
  - kind: ServiceAccount
    name: kaniko-sa
roleRef:
  kind: Role
  name: kaniko-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}