---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-extended-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - patch
      - delete
      - list
      - watch
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch