apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-zoo-project

build:
  platforms: ["linux/amd64"]

deploy:
  helm:
    releases:
      - name: zoo-project-dru
        remoteChart: zoo-project/zoo-project-dru
        namespace: eoap-zoo-project
        createNamespace: true
        version: 0.8.2
        valuesFiles: 
        - values.yaml
        setValues:
          iam.enabled: false
          cookiecutter.templateUrl: https://github.com/GeoLabs/zoo-service-template.git
          cookiecutter.templateBranch: feature/eoap-tooling
          filter_in.enabled: true
          filter_out.enabled: true
          persistence.procServicesAccessMode: ReadWriteMany
          websocketd.enabled: true
          websocketd.port: 8888
          websocketd.image.repository: zooproject/websocketd
          websocketd.image.tag: 67449315857b54bbc970f02c7aa4fd10a94721f0
          websocketd.image.pullPolicy: IfNotPresent
          rabbitmq.autoSetup.enabled: true
          redis.enabled: true
          workflow.additionalInputs:
            s3_bucket: results
            region_name: us-east-1
            aws_secret_access_key: test
            aws_access_key_id: test
            endpoint_url: http://eoap-zoo-project-localstack.eoap-zoo-project.svc.cluster.local:4566

      - name: eoap-zoo-project-coder
        chartPath: ../charts/coder
        namespace: eoap-zoo-project
        createNamespace: true
        setValues:
          coder.coderImage: eoepca/pde-code-server:1.0.0
          coder.workspace: ogc-api-processes-with-zoo
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true

        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
      - name: eoap-zoo-project-localstack
        remoteChart: localstack/localstack
        namespace: eoap-zoo-project
        createNamespace: true
        setValues:
          service.type: ClusterIP

profiles:

  - name: macos

    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues/zoofpm.image.pullPolicy
        value: Never
      - op: add
        path: /deploy/helm/releases/0/setValues/zookernel.image.pullPolicy
        value: Never
      - op: add
        path: /deploy/helm/releases/0/setValues/workflow.storageClass
        value: hostpath
      - op: add
        path: /deploy/helm/releases/0/setValues/workflow.argo.storageClass
        value: hostpath
      - op: add
        path: /deploy/helm/releases/0/setValues/persistence.storageClass
        value: hostpath
      - op: add
        path: /deploy/helm/releases/0/setValues/persistence.procServicesStorageClass
        value: hostpath
      - op: add
        path: /deploy/helm/releases/0/setValues/persistence.tmpStorageClass
        value: hostpath
      - op: add
        path: /deploy/helm/releases/1/setValues/coder.storageClassName
        value: hostpath
      - op: add
        path: /deploy/helm/releases/1/setValues/calrissian.storageClassName
        value: hostpath

  - name: keda

    patches:
      # Install Kyverno FIRST so CRDs exist before applying policies
      - op: add
        path: /deploy/helm/releases/0
        value:
          name: kyverno
          remoteChart: kyverno/kyverno
          version: "3.5.2"
          namespace: kyverno-system
          wait: true
          createNamespace: true
          setValues:
            crds.install: true

      # Enable KEDA + protections on zoo-project-dru (now at index 1)
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.skipScaledObject
        value: false
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.triggers.postgresql.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.triggers.postgresql.useConfigMap
        value: false
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.triggers.postgresql.query
        value: "SELECT COUNT(*) FROM workers WHERE status = 1"
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.triggers.rabbitmq.enabled
        value: true

      # Kyverno protections (requires Kyverno CRDs installed above)
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.kyverno.enabled
        value: false
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.kyverno.policies.zoofpmProtection.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.kyverno.policies.zoofpmProtection.failurePolicy
        value: Enforce

      # Eviction Controller to protect active workers
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.evictionController.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.evictionController.image.repository
        value: ghcr.io/zoo-project/zoofpm-eviction-controller
      - op: add
        path: /deploy/helm/releases/1/setValues/keda.evictionController.image.tag
        value: latest

  - name: argo

    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value: ["values_argo.yaml"]
      - op: replace
        path: /deploy/helm/releases/0/setValues/cookiecutter.templateUrl
        value: https://github.com/gfenoy/zoo-argo-wf-proc-service-template.git
      - op: replace
        path: /deploy/helm/releases/0/setValues/cookiecutter.templateBranch
        value: feature/use-argo-wf-namespace

    portForward:
      # Argo Workflows Server
      - resourceType: service
        resourceName: zoo-project-dru-argo-workflows-server
        namespace: eoap-zoo-project
        port: 2746
        localPort: 2746
      # ZOO-Project services
      - resourceType: service
        resourceName: zoo-project-dru-service
        namespace: eoap-zoo-project
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: zoo-project-dru-websocketd
        namespace: eoap-zoo-project
        port: 8888
        localPort: 8888
      # LocalStack S3
      - resourceType: service
        resourceName: eoap-zoo-project-localstack
        namespace: eoap-zoo-project
        port: 4566
        localPort: 9000
      # Code-server
      - resourceType: service
        resourceName: code-server-service
        namespace: eoap-zoo-project
        port: 8080
        localPort: 8000

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-zoo-project
    address: localhost
    port: 8080
    localPort: 8000
  - resourceType: service
    resourceName: zoo-project-dru-websocketd
    namespace: eoap-zoo-project
    port: 8888
    localPort: 8888
  - resourceType: service
    resourceName: zoo-project-dru-service
    namespace: eoap-zoo-project  
    address: localhost
    port: 80
    localPort: 8080  