apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-zoo-project
    
deploy:
  helm:
    releases:
      - name: zoo-project-dru
        remoteChart: zoo-project/zoo-project-dru
        namespace: eoap-zoo-project
        createNamespace: true
        version: 0.3.0
        valuesFiles: []
        setValues:
          iam.enabled: false
      - name: eoap-zoo-project-coder
        chartPath: ../charts/coder
        namespace: eoap-zoo-project
        createNamespace: true
        setValues:
          coder.coderImage: eoepca/pde-code-server:1.0.0
          coder.workspace: ogc-api-processes-with-zoo
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
      - name: eoap-zoo-project-localstack
        remoteChart: localstack/localstack
        namespace: eoap-zoo-project
        createNamespace: true
        setValues:
          service.type: ClusterIP

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-zoo-project
    port: 8080
    localPort: 8000  
  - resourceType: service
    resourceName: zoo-project-dru-service
    namespace: eoap-zoo-project  
    port: 80
    localPort: 8080  