apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: event-driven-sensor
spec:
  eventBusName: jetstream-event-bus
  template:
    serviceAccountName: argo
  dependencies:
    - name: redis-stream
      eventSourceName: redis-stream-source
      eventName: acquisition-event
  triggers:
    - template:
        name: water-bodies-detection-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: water-bodies-detection-
                namespace: eoap-event-driven
              spec:
                serviceAccountName: argo
                entrypoint: main
                arguments:
                  parameters:
                  - name: items
                  - name: aoi
                workflowTemplateRef:
                  name: water-bodies-detection
          parameters:
            - src:
                dependencyName: redis-stream
                dataKey: values.items
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: redis-stream
                dataKey: values.aoi
              dest: spec.arguments.parameters.1.value