apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: jetstream-event-bus
spec:
  jetstream:
    version: latest 
    replicas: {{ .Values.jetstreamReplicas }}
    persistence: 
        storageClassName: standard
        accessMode: ReadWriteOnce
        volumeSize: {{ .Values.jetstreamVolumeSize }}
    streamConfig: |             
      maxAge: 24h
    settings: |
      max_file_store: 1GB       
    startArgs:
      - "-D"                    