apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-dask-gateway

build:
  artifacts:
    - image: worker
      context: .
      docker:
        dockerfile: Dockerfile.worker
    - image: daskclient
      context: .
      docker:
        dockerfile: Dockerfile.client
    - image: coder 
      context: .
      docker:
        dockerfile: Dockerfile.coder

deploy:
  helm:
    releases:
      - name: dask-gateway
        remoteChart: https://helm.dask.org/dask-gateway-2024.1.0.tgz
        namespace: eoap-dask-gateway
        createNamespace: true
        valuesFiles:
          - values.yaml
        setValueTemplates:
          gateway.backend.image.name: "{{.IMAGE_NAME_worker}}"
          gateway.backend.image.tag: "{{.IMAGE_TAG_worker}}"
          traefik.service.type: "ClusterIP"

      - name: eoap-dask-gateway
        chartPath: ../charts/coder
        namespace: eoap-dask-gateway
        createNamespace: true
        setValueTemplates:
          coder.coderImage: "{{.IMAGE_NAME_coder}}"
          daskGateway.image: "{{.IMAGE_NAME_worker}}:{{.IMAGE_TAG_worker}}"
        setValues:
          coder.workspace: dask-app-package
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true
          daskGateway.enabled: true
          daskGateway.daskGatewayUrl: "http://traefik-dask-gateway.eoap-dask-gateway.svc.cluster.local:80"
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
      - name: eoap-dask-gateway-localstack
        remoteChart: localstack/localstack
        namespace: eoap-dask-gateway
        createNamespace: true
        setValues:
          service.type: ClusterIP
    hooks:
      before: []
      after:
        - host:
            command: ["sh", "-c", "./wait-for-it.sh"]
            os: [darwin, linux]

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-dask-gateway 
    address: localhost
    port: 8080
    localPort: 8000
  - resourceType: service
    resourceName: traefik-dask-gateway
    namespace: eoap-dask-gateway
    address: localhost
    port: 80
    localPort: 8001