apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-mastering-app-package
    
deploy:
  helm:
    releases:
      - name: eoap-mastering-app-package
        chartPath: ../charts/coder
        namespace: eoap-mastering-app-package
        createNamespace: true
        setValues:
          coder.coderImage: eoepca/pde-code-server:1.0.0
          coder.workspace: mastering-app-package
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
      - name: eoap-mastering-app-package-localstack
        remoteChart: localstack/localstack
        namespace: eoap-mastering-app-package
        createNamespace: true
        setValues:
          service.type: ClusterIP

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-mastering-app-package 
    port: 8080
    localPort: 8000  # Port on your local machine