apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-application-package-patterns

deploy:
  helm:
    releases:
      - name: eoap-application-package-patterns
        chartPath: ../charts/coder
        namespace: eoap-application-package-patterns
        createNamespace: true
        setValues:
          coder.workspace: application-package-patterns
          coder.storageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true
          calrissian.storageClassName: standard
          calrissian.imagePullSecrets: []
          skaffold.enabled: True
          kaniko.enabled: true
   
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }

      - name: eoap-application-package-patterns-localstack
        remoteChart: localstack/localstack
        namespace: eoap-application-package-patterns
        createNamespace: true
        setValues:
          service.type: ClusterIP

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-application-package-patterns
    port: 8080
    localPort: 8000