apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-cwl
    
deploy:
  helm:
    releases:
      - name: eoap-cwl
        chartPath: ../charts/coder
        namespace: eoap-cwl
        createNamespace: true
        setValues:
          coder.coderImage: eoepca/pde-code-server:1.0.0
          coder.workspace: cwl-eoap
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-cwl
    port: 8080
    localPort: 8000  # Port on your local machine